### ISSUE TITLE
Ask -annotation dataset

### ISSUE THREAD

**Issue by arumrum** [1297rohit/RCNN#1]
Hello..this source code is very helpfull to me because I can study the rcnn concept. I want to ask about the annotation dataset. How can I make the annotation dataset by myself?

Thank you for your help
Regards
Arum

**Comment by 1297rohit** [comment]
Hi Arum,
You can use any of the annotation tool for annotating your dataset.
One of the tool can be this : https://github.com/puzzledqs/BBox-Label-Tool

**Comment by arumrum** [comment]
Thank you very much !! :)
