### ISSUE TITLE
Memory Error: Unable to allocate memory 

### ISSUE THREAD

**Issue by priyamehta01** [1297rohit/RCNN#2]
When performing this step
``trdata = ImageDataGenerator(horizontal_flip=True, vertical_flip=True, rotation_range=90)
traindata = X_train.flow(x=X_train, y=y_train)
tsdata = ImageDataGenerator(horizontal_flip=True, vertical_flip=True, rotation_range=90)
testdata = X_test.flow(x=X_test, y=y_test)``

I am getting such an error
MemoryError: Unable to allocate array with shape (26936, 224, 224, 3) and data type float32

How could I go about this?

**Comment by 1297rohit** [comment]
Hello this error is due to less availability of memory. To go about this you need to free memory from previous variables by using del(). I have implemented it in google colab. You can access it in the link https://colab.research.google.com/drive/1ec6NffTuM0X1rsWE_wbqwoAfxFMz3oFB
