### ISSUE TITLE
hi,I found some mistake in notebook

### ISSUE THREAD

**Issue by zky001** [1297rohit/RCNN#5]
In last cell 'model_loaded' is not defined
![error](https://i.loli.net/2020/07/02/m9HqkfN3SF6cZp2.png)

**Comment by zky001** [comment]
just change model_loaded to model_final ,then mistake are repaired
![correct](https://i.loli.net/2020/07/02/luIsA1YrvLmF2Tw.png)

**Comment by 1297rohit** [comment]
Hello thanks for pointing it out. I have made changes in the code.
