### ISSUE TITLE
Using for more than 2 classes 

### ISSUE THREAD

**Issue by siddhi5386** [1297rohit/RCNN#6]
i want to use this for detecting 2 classes: buildings and trees..
can you pls help me with the code.
I am getting problem in preparing the datasets
if i convert my xml file to csv file..the labels corresponding to buildings(1) and trees(0) are lost (labelling tool used is labelImg)
what can be done to mark the labels in the code as it can not be done using the iou values in my case.

please help

**Comment by 1297rohit** [comment]
Your xml to csv code may have same issue. Share the code snippet here so that we can look into it.

**Comment by 1297rohit** [comment]
As the problem is with the conversion code and not with the RCNN code and since there is no response so closing the issue.

**Comment by siddhi5386** [comment]
Sir, I have solved it myself.
Thankss
