### ISSUE TITLE
Running the notebook

### ISSUE THREAD

**Issue by JVedant** [1297rohit/RCNN#7]
Hi,
I tried running the notebook but even on rtx-3090(24gb) i wasn't able to run the code due to the high memory requirements of VGG16, so i tried to reduce the image size to **(56,56, 3)** along VGG16(**include_top=Flase**, **input_shape=(56,56,3)**, weights='imagenet') and it worked.

it would be great if you can change the transfer learning model to ResNet50 or somewhat similar along with reducing the image size to somewhat smaller in the notebook as not everyone would be able to train this huge model.

Anyways, I appreciate your efforts in explaining the concept on Medium.
Great work !

**Comment by 1297rohit** [comment]
Hello i have created a colab notebook as well for RCNN. In that notebook i have freed memory time to time so that it can run in colab. You can try that as well. And for local system you can store the output of the selective search in npy format to run it on lower configuration system.
